stages:
  - build
  - deploy

# STEP 1: Build the ICS file
build_calendar:
  retry: 1
  stage: build
  image: python:3.11
  before_script:
    - pip install -r requirements.txt
  script:
    # Debugging: show environment
    - echo "SRT_IDEN is $SRT_IDEN"
    - python generate_ics.py --out calendar.ics --token "$PUBLISH_DIR_TOKEN"
  artifacts:
    paths:
      - calendar.ics          # Save the generated calendar folder for next stage
    expire_in: 1 hour

# STEP 2: Deploy to GitLab Pages
pages:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying calendar to GitLab Pages..."
    - mv calendar.ics public   # GitLab Pages requires a "public" folder
  artifacts:
    paths:
      - public
  only:
    - main                 # Only deploy from main branch
